2025-02-24T02:06:19.0237681Z ##[group]Run actions/setup-python@v5
2025-02-24T02:06:19.0238571Z with:
2025-02-24T02:06:19.0239067Z   python-version: 3.9
2025-02-24T02:06:19.0239653Z   cache: pip
2025-02-24T02:06:19.0240423Z   check-latest: false
2025-02-24T02:06:19.0241336Z   token: ***
2025-02-24T02:06:19.0241898Z   update-environment: true
2025-02-24T02:06:19.0242631Z   allow-prereleases: false
2025-02-24T02:06:19.0243296Z ##[endgroup]
2025-02-24T02:06:19.1938675Z ##[group]Installed versions
2025-02-24T02:06:19.2000487Z Successfully set up CPython (3.9.21)
2025-02-24T02:06:19.2002958Z ##[endgroup]
2025-02-24T02:06:19.2537012Z [command]/opt/hostedtoolcache/Python/3.9.21/x64/bin/pip cache dir
2025-02-24T02:06:19.5404354Z /home/runner/.cache/pip
2025-02-24T02:06:19.6415323Z ##[warning]Cache not found for keys: setup-python-Linux-x64-24.04-Ubuntu-python-3.9.21-pip-91d90556e6b943c05d069084bc8cbcbd49e4bfe3709354780feecc28d856cb9e, setup-python-Linux-x64-24.04-Ubuntu-python-3.9.21-pip
2025-02-24T02:06:19.6422582Z pip cache is not found
